name: Deploy to Tencent Cloud Webify

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build static files
        run: npm run export
        env:
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_SITE_NAME: "短剧调色培训"

      - name: Deploy to Tencent Cloud Webify
        uses: TencentCloudBase/cloudbase-action@v2
        with:
          secretId: ${{ secrets.TENCENT_SECRET_ID }}
          secretKey: ${{ secrets.TENCENT_SECRET_KEY }}
          envId: ${{ secrets.TENCENT_ENV_ID }}
          staticSrcPath: out
